services:
  frontend:
    image: ghcr.io/zj145013/role-prompt-generation-frontend:main
    ports:
      - "8184:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/zj145013/role-prompt-generation-backend:main
    ports:
      - "8186:8000"
    restart: unless-stopped
